#!/bin/bash
#load_file_n 367 3
#    load_file 367 366 365 364

#check if it exists 
if [ "$0" == "" ]; then
    exit 1
fi

IFS='x' read -ra ADDR <<< "$2"

f="${ADDR[0]}"
s="${ADDR[1]}"
it=$(($f-$s))

for i in $(seq $it $f)
do
    echo "load_file $i"
done


