#!/usr/bin/python
import re


DIALOG_FILE = "/home/user/dialogs" #output of dialog_list

RGET = r'^(User|Chat) (.+)\:'

with open(DIALOG_FILE, "r") as f:
    lines = f.readlines()
    result = [re.match(RGET, line, flags=0) for line in lines]
    result = [r.group(2).replace(" ", "_") for r in result if r != None]
    result = ['mark_read {}'.format(r) for r in result]
    print "\n".join(result)

